# Default values for couchpotato.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: linuxserver/couchpotato
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

couchpotato:
  # User and group to run container as See https://github.com/linuxserver/docker-couchpotato#user--group-identifiers for information
  puid: 1000
  pgid: 1000
  # Timezone in which you are located See options at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  timezone: America/Chicago
  # Configures the config.ini with all preconfigured values that you want. See #TBD for all the different configuration options you
  # if you do not supply values here it will generate one for you on first boot
  # port: 5050
  settings:
    # core:
    #   port: 5050
    #   url_base: ""
    #   show_wizard: True

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
persistance:
  enabled: true
  volumes:
    - name: config
      hostPath:
        path: /shared/config/couchpotato
        type: DirectoryOrCreate
    - name: downloads
      hostPath:
        path: /shared/downloads
        type: DirectoryOrCreate
    - name: torrents
      hostPath:
        path: /shared/torrents
        type: DirectoryOrCreate
    - name: movies
      hostPath:
        path: /shared/media/movies
        type: DirectoryOrCreate

  volumeMounts:
    - name: config
      mountPath: /config
    - name: downloads
      mountPath: /config
    - name: config
      mountPath: /config
    - name: torrents
      mountPath: /torrents

nodeSelector: {}

tolerations: []

affinity: {}
