apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "couchpotato.fullname" . }}
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "couchpotato.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "couchpotato.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "couchpotato.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.couchpotato.port | default 5050 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or .Values.persistance.enabled .Values.couchpotato.settings }}
      volumes:
        {{- if .Values.couchpotato.settings }}
        - name: config.ini
          configMap:
            name: {{ include "couchpotato.fullname" . }}
            items:
              - key: config.ini
                path: config.ini
        {{- end}}
      {{- toYaml .Values.persistance.volumes | nindent 8 }}  
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
