apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "couchpotato.fullname" . }}
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "couchpotato.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "couchpotato.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "couchpotato.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if and .Values.couchpotato.createInitialConfig .Values.couchpotato.settings }}
      initContainers:
        - name: init-config
          image: busybox
          {{- if or .Values.persistance.enabled .Values.couchpotato.settings }}
          securityContext:
            runAsUser: 1000
          volumeMounts:
            {{- if .Values.couchpotato.settings }}
            - name: settings
              mountPath: /tmp
            {{- end }}
            {{- toYaml .Values.persistance.volumeMounts | nindent 12 }}
          {{- end }}
          command: ['sh', '-c']
          args: ['cp /tmp/config.ini /config']
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: {{ .Values.couchpotato.puid | quote }}
            - name: PGID
              value: {{ .Values.couchpotato.pgid | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.couchpotato.port | default 5050 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if .Values.persistance.enabled }}
          volumeMounts:
            {{- toYaml .Values.persistance.volumeMounts | nindent 12 }}
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or .Values.persistance.enabled .Values.couchpotato.settings }}
      volumes:
        {{- if .Values.couchpotato.settings }}
        - name: settings
          configMap:
            name: {{ include "couchpotato.fullname" . }}
            items:
              - key: config.ini
                path: config.ini
        {{- end}}
      {{- toYaml .Values.persistance.volumes | nindent 8 }}  
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
