apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchpotato.fullname" . }}
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.couchpotato.port | default 5050 }}
      protocol: TCP
      name: web
  selector:
    {{- include "couchpotato.selectorLabels" . | nindent 4 }}
